NAME = ex01

SOURCES = main.cpp Zombie.cpp zombieHorde.cpp \

OBJECTS = $(SOURCES:%.cpp=%.o)

CC = C++
CPPFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME):$(OBJECTS)
	$(CC) $(CPPFLAGS) $(OBJECTS) -o $(NAME)

clean:
	/bin/rm -f $(OBJECTS)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all

test: all
	./$(NAME)